import "tailwindcss/tailwind.css"
// import "src/styles/globals.css"
import Head from "next/head"
import { Layout } from "src/components/Layout"
import { Header } from "src/components/Header"

const MyApp = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Layout>
        <div className="text-red-500">test</div>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}

export default MyApp
